<?xml version="1.0" encoding="UTF-8"?><testsuite name="nosetests" tests="1" errors="0" failures="1" skip="0"><testcase classname="test_generate_date" name="test_increase_month" time="0.000"><failure type="builtins.AssertionError" message=""><![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/usr/local/lib/python3.6/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/erick/Nextcloud/CMCB/bookings_scripts/test_generate_date.py", line 21, in test_increase_month
    assert increase_month(input) == "2015-12-01T00:00:00.00000Z"
AssertionError
]]></failure></testcase></testsuite>